"""
Authentication schemas.
Generated by PHP to FastAPI converter.
"""

from pydantic import BaseModel


class Token(BaseModel):
    """Token response schema."""
    access_token: str
    token_type: str


class UserLogin(BaseModel):
    """User login schema."""
    username: str
    password: str


class UserBase(BaseModel):
    """User base schema."""
    username: str
    email: str


class UserCreate(UserBase):
    """User creation schema."""
    password: str


class User(UserBase):
    """User response schema."""
    id: int
    is_active: bool
    
    class Config:
        orm_mode = True
