"""
Item schemas.
Generated by PHP to FastAPI converter.
"""

from typing import Optional
from pydantic import BaseModel


class ItemBase(BaseModel):
    """Item base schema."""
    name: str
    description: Optional[str] = None


class ItemCreate(ItemBase):
    """Item creation schema."""
    pass


class ItemUpdate(ItemBase):
    """Item update schema."""
    name: Optional[str] = None


class Item(ItemBase):
    """Item response schema."""
    id: int
    owner_id: Optional[int] = None
    
    class Config:
        orm_mode = True
